; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
upload_speed = 115200
upload_resetmethod = nodemcu
upload_flags = 
	--before
	default_reset
	--after
	hard_reset
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/DHT sensor library@^1.4.6
	olikraus/U8g2@^2.36.12
	mobizt/FirebaseClient@^2.2.2
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.5
	tzapu/WiFiManager@^2.0.17
	https://github.com/mathieucarbou/AsyncTCP.git
